#!/usr/bin/env python
"""
Django command-line utility for the Sky Engineering Portal.

This file is generated by Django and is used for commands such as:
    py manage.py runserver
    py manage.py migrate
    py manage.py test

It should stay at the root of the Django project folder.
"""

import os
import sys


def main():
    """Run Django management commands."""
    # Tell Django which settings module to load for this project.
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'sky_engineering.settings')

    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        # This error usually means Django is not installed or the virtual
        # environment has not been activated.
        raise ImportError(
            "Couldn't import Django. Make sure it is installed and available "
            "on your PYTHONPATH environment variable. Did you forget to activate "
            "a virtual environment?"
        ) from exc

    # Pass the terminal command through to Django.
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
