# Generated by Django 6.0.2 on 2026-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(max_length=254)),
                ('purpose', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
